spring:
  application:
    name: invoice-service
  profiles:
    active: ${PROFILE:dev}
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMS_PORT:5672}
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASSWORD:guest}

server:
  port: 8085